server:
    port: 8080

spring:
    # 数据库访问配置
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/mdb?useUnicode=true&characterEncoding=utf8&autoConnect=true&rewriteBatchedStatements=TRUE&allowMultiQueries=true&useSSL=false
        username: ENC(qlHsL98xQYPgeZz2sP5SYw==)
        password: ENC(9PiUhxwfrOCUjwGL86KrWHz2iGf/UTKl)
        # 初始化大小，最小，最大
        initial-size: 5
        min-idle: 5
        max-active: 20
        # 配置获取连接等待超时的时间
        max-wait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        time-between-eviction-runsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        validation-query: SELECT 1
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        pool-preparedStatements: true
        max-pool-prepared-statement-per-connection-size: 20
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,log4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

beetlsql:
    basePackage: panzer.vor.generate.easyopen.repository
    daoSuffix: Dao
    sqlPath: /sql
    nameConversion: org.beetl.sql.core.UnderlinedNameConversion
    dbStyle: org.beetl.sql.core.db.MySqlStyle
    dev: true

jasypt:
    encryptor:
        password: monkeykingba
